# Generated by Django 4.2.11 on 2024-05-01 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('F', '여성')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
