# Generated by Django 4.2.11 on 2024-05-01 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduce',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
