# Generated by Django 4.2.11 on 2024-04-30 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='author',
        ),
    ]
